version: '3.8'
services:
  # Node.js/React service
  frontend:
    image: node:18
    volumes:
      - ./frontend:/app
    working_dir: /app
    command: npm start
    ports:
      - "3000:3000"
    depends_on:
      - backend

  # PHP/Laravel service
  backend:
    image: php:8.2-apache
    volumes:
      - ./backend:/var/www/html
    ports:
      - "8000:80"
    environment:
      DB_CONNECTION: mysql
      DB_HOST: db
      DB_PORT: 3306
      DB_DATABASE: laravel_db
      DB_USERNAME: root
      DB_PASSWORD: secret
    depends_on:
      - db

  # MySQL service
  db:
    image: mysql:8.0.39
    environment:
      MYSQL_DATABASE: laravel_db
      MYSQL_ROOT_PASSWORD: secret
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
